const sucursalesSonora = [
  {
    nombre: 'Sucursal Miguel Aleman',
    direccion: 'Av. Miguel Aleman 3985 - Local 5',
    colonia: 'Col. Centro',
    ciudad: 'Ciudad Obregon',
    telefono: '644 415 2541',
    imagen: '/images/nvo-horizonte.webp',
    mapsUrl: 'https://maps.google.com/?q=Av.+Ju%C3%A1rez+123',
  },
  {
    nombre: 'Sucursal Central',
    direccion: 'Rodolfo Elias Calles 723 pte - Local B',
    colonia: 'Col. Prados del Tepeyac',
    ciudad: 'Ciudad Obregon',
    telefono: '644 412 7277',
    imagen: '/images/sucursal-norte.jpg',
    mapsUrl: 'https://maps.google.com/?q=Calle+Reforma+456',
  },
  {
    nombre: 'Sucursal Paris',
    direccion: 'Rodolfo Elias Calles 1787',
    colonia: 'Col. Fovisste 2',
    ciudad: 'Ciudad Obregon',
    telefono: '644 690 9779',
    imagen: '/images/nvo-horizonte.webp',
    mapsUrl: 'https://maps.google.com/?q=Av.+Ju%C3%A1rez+123',
  },
  {
    nombre: 'Sucursal Galeana',
    direccion: 'C. Galeana 817',
    colonia: 'Col. Centro',
    ciudad: 'Ciudad Obregon',
    telefono: '644 144 1208',
    imagen: '/images/sucursal-norte.jpg',
    mapsUrl: 'https://maps.google.com/?q=Calle+Reforma+456',
  },
  {
    nombre: 'Sucursal Jalisco',
    direccion: 'Plaza Ley Jalisco - Local 10',
    colonia: 'Municipio Libre',
    ciudad: 'Ciudad Obregon',
    telefono: '644 179 0634',
    imagen: '/images/nvo-horizonte.webp',
    mapsUrl: 'https://maps.google.com/?q=Av.+Ju%C3%A1rez+123',
  },
  {
    nombre: 'Sucursal Plano Oriente',
    direccion: 'No reeleccion 1621',
    colonia: 'Col. Benito Juarez',
    ciudad: 'Ciudad Obregon',
    telefono: '644 688 1827',
    imagen: '/images/sucursal-norte.jpg',
    mapsUrl: 'https://maps.google.com/?q=Calle+Reforma+456',
  },
  {
    nombre: 'Sucursal Guerrero',
    direccion: 'C. Guerrero 2258',
    colonia: 'Infonavit Yucujimari',
    ciudad: 'Ciudad Obregon',
    telefono: '644 414 5920',
    imagen: '/images/nvo-horizonte.webp',
    mapsUrl: 'https://maps.google.com/?q=Av.+Ju%C3%A1rez+123',
  },
  {
    nombre: 'Sucursal Hermosillo',
    direccion: 'Av. Morelia 18',
    colonia: 'Col. Centro',
    ciudad: 'Hermosillo',
    telefono: '662 217 9259',
    imagen: '/images/sucursal-norte.jpg',
    mapsUrl: 'https://maps.google.com/?q=Calle+Reforma+456',
  },
  {
    nombre: 'Sucursal Gaymas',
    direccion: 'Av. Serdan 01',
    colonia: 'Col. Centro',
    ciudad: 'Guaymas',
    telefono: '622 113 2369',
    imagen: '/images/nvo-horizonte.webp',
    mapsUrl: 'https://maps.google.com/?q=Av.+Ju%C3%A1rez+123',
  },
  {
    nombre: 'Sucursal Huatabampo',
    direccion: 'C. Hidalgo 19',
    colonia: 'Col. Centro',
    ciudad: 'Huatabampo',
    telefono: '647 112 1408',
    imagen: '/images/sucursal-norte.jpg',
    mapsUrl: 'https://maps.google.com/?q=Calle+Reforma+456',
  },
];

export default sucursalesSonora;
